site_name: Data Science
docs_dir: '../../docs/fr'
site_dir: '../../generated/fr'                      # Where to put the English HTML files
site_url: https://datascience_careerera.fr/


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material

nav: 
  - 'Introduction à la Data Science': 'intro.md'
  - 'Apprentissage automatique (a.k.a Machine Learning)': 'ml.md'